/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DistributionRouteImport } from './routes/distribution'
import { Route as MaitreRouteImport } from './routes/maitre'
import { Route as NouvellePartieRouteImport } from './routes/nouvelle-partie'
import { Route as ReglesRouteImport } from './routes/regles'
import { Route as RejoindreRouteImport } from './routes/rejoindre'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as TourDeTableRouteImport } from './routes/tour-de-table'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributionRoute = DistributionRouteImport.update({
  id: '/distribution',
  path: '/distribution',
  getParentRoute: () => rootRouteImport,
} as any)
const MaitreRoute = MaitreRouteImport.update({
  id: '/maitre',
  path: '/maitre',
  getParentRoute: () => rootRouteImport,
} as any)
const NouvellePartieRoute = NouvellePartieRouteImport.update({
  id: '/nouvelle-partie',
  path: '/nouvelle-partie',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglesRoute = ReglesRouteImport.update({
  id: '/regles',
  path: '/regles',
  getParentRoute: () => rootRouteImport,
} as any)
const RejoindreRoute = RejoindreRouteImport.update({
  id: '/rejoindre',
  path: '/rejoindre',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const TourDeTableRoute = TourDeTableRouteImport.update({
  id: '/tour-de-table',
  path: '/tour-de-table',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/distribution': typeof DistributionRoute
  '/maitre': typeof MaitreRoute
  '/nouvelle-partie': typeof NouvellePartieRoute
  '/regles': typeof ReglesRoute
  '/rejoindre': typeof RejoindreRoute
  '/roles': typeof RolesRoute
  '/tour-de-table': typeof TourDeTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/distribution': typeof DistributionRoute
  '/maitre': typeof MaitreRoute
  '/nouvelle-partie': typeof NouvellePartieRoute
  '/regles': typeof ReglesRoute
  '/rejoindre': typeof RejoindreRoute
  '/roles': typeof RolesRoute
  '/tour-de-table': typeof TourDeTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/distribution': typeof DistributionRoute
  '/maitre': typeof MaitreRoute
  '/nouvelle-partie': typeof NouvellePartieRoute
  '/regles': typeof ReglesRoute
  '/rejoindre': typeof RejoindreRoute
  '/roles': typeof RolesRoute
  '/tour-de-table': typeof TourDeTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/distribution'
    | '/maitre'
    | '/nouvelle-partie'
    | '/regles'
    | '/rejoindre'
    | '/roles'
    | '/tour-de-table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/distribution'
    | '/maitre'
    | '/nouvelle-partie'
    | '/regles'
    | '/rejoindre'
    | '/roles'
    | '/tour-de-table'
  id:
    | '__root__'
    | '/'
    | '/distribution'
    | '/maitre'
    | '/nouvelle-partie'
    | '/regles'
    | '/rejoindre'
    | '/roles'
    | '/tour-de-table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DistributionRoute: typeof DistributionRoute
  MaitreRoute: typeof MaitreRoute
  NouvellePartieRoute: typeof NouvellePartieRoute
  ReglesRoute: typeof ReglesRoute
  RejoindreRoute: typeof RejoindreRoute
  RolesRoute: typeof RolesRoute
  TourDeTableRoute: typeof TourDeTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribution': {
      id: '/distribution'
      path: '/distribution'
      fullPath: '/distribution'
      preLoaderRoute: typeof DistributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maitre': {
      id: '/maitre'
      path: '/maitre'
      fullPath: '/maitre'
      preLoaderRoute: typeof MaitreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nouvelle-partie': {
      id: '/nouvelle-partie'
      path: '/nouvelle-partie'
      fullPath: '/nouvelle-partie'
      preLoaderRoute: typeof NouvellePartieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regles': {
      id: '/regles'
      path: '/regles'
      fullPath: '/regles'
      preLoaderRoute: typeof ReglesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rejoindre': {
      id: '/rejoindre'
      path: '/rejoindre'
      fullPath: '/rejoindre'
      preLoaderRoute: typeof RejoindreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour-de-table': {
      id: '/tour-de-table'
      path: '/tour-de-table'
      fullPath: '/tour-de-table'
      preLoaderRoute: typeof TourDeTableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DistributionRoute: DistributionRoute,
  MaitreRoute: MaitreRoute,
  NouvellePartieRoute: NouvellePartieRoute,
  ReglesRoute: ReglesRoute,
  RejoindreRoute: RejoindreRoute,
  RolesRoute: RolesRoute,
  TourDeTableRoute: TourDeTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
